#!/usr/bin/env bash

set -eux

KERNEL="${1}"
shift || true
QEMU_OPTIONS=("${@}")

QEMU="${QEMU:-qemu-system-riscv64}"
CPUS="${CPUS:-4}"
MEM="${MEM:-4G}"

"${QEMU}" \
    -machine virt \
    -bios default \
    -smp "${CPUS}" \
    -m "${MEM}" \
    -kernel "${KERNEL}" \
    -nographic \
    -global virtio-mmio.force-legacy=false \
    -serial mon:stdio \
    --no-reboot \
    "${QEMU_OPTIONS[@]}"
